# Generated by Django 5.1.5 on 2025-01-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
